Implemented webview screenshot feature
xaynetwork/plugins pull request #1
Opened 2021-02-15 10:08 UTC by carminetoriello

## Description

It introduces the possibility to take a screenshot of the content that is displayed in the webview.

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-02-15 11:46 UTC, peterstojanowski requested changes

2021-02-15 11:46 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/FlutterWebView.m
> +  UIGraphicsBeginImageContextWithOptions(_webView.bounds.size,YES, _webView.contentScaleFactor);
Is `takeSnapshotWithConfiguration:` not working for you? We should be using the proper api for this.

2021-02-16 15:44 UTC, joecks commented on packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
> +    int height = (int) (webView.getContentHeight() * scale + 0.5);
what is that magical 0.5?

2021-02-16 15:44 UTC, joecks commented on packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
> +    // view.setDrawingCacheEnabled(false);
from my perspective this can be removed

2021-02-16 15:44 UTC, joecks commented on packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
> +    resized.compress(Bitmap.CompressFormat.PNG, 50, stream);
nit: So this should be potentially a blocking slow call. Nothing too crazy, but why don't you do that on the flutter side? Anyway, I am thinking of other devices that have big screens. On the other hand it might be handy to provide the output size as a input of takeScreenShot(result, width, height) where width=height=0 means give me what you have.

2021-02-17 08:55 UTC, carminetoriello commented on packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
> +    // view.setDrawingCacheEnabled(false);
Sure!

2021-02-17 08:56 UTC, carminetoriello commented on packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
> +    int height = (int) (webView.getContentHeight() * scale + 0.5);
Removed, useless

2021-02-17 08:59 UTC, carminetoriello commented on packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
> +    resized.compress(Bitmap.CompressFormat.PNG, 50, stream);
Do you mean doing the resizing and the compression on the Flutter side ?

2021-02-17 10:41 UTC, carminetoriello commented on packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
> +    resized.compress(Bitmap.CompressFormat.PNG, 50, stream);
In the meanwhile I've done some tests where I've awaited for the screenshot and then navigated back to another screen and it always took close to a second in debug mode (tested also with webview content with few images in it). 
Maybe we could keep it like this for now and see how it works and then change it if needed

2021-02-17 10:45 UTC, joecks commented on packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
> +    resized.compress(Bitmap.CompressFormat.PNG, 50, stream);
yes that would be fine. I am just concerned that it will block on the android side. But for now lets go with it

2021-02-17 10:53 UTC, peterstojanowski approved these changes

2021-02-17 10:56 UTC, merged

2021-02-17 11:00 UTC, joecks commented on packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
> +    resized.compress(Bitmap.CompressFormat.PNG, 50, stream);
Lets align with with the iOS operation. I just want to double check here.

Also have a look at the docs of compress:

 ```
 @WorkerThread
 public boolean compress(CompressFormat format, int quality, OutputStream stream) {
        checkRecycled("Can't compress a recycled bitmap");
        // do explicit check before calling the native method
        if (stream == null) {
            throw new NullPointerException();
        }
        if (quality < 0 || quality > 100) {
            throw new IllegalArgumentException("quality must be 0..100");
        }
        StrictMode.noteSlowCall("Compression of a bitmap is slow");
        Trace.traceBegin(Trace.TRACE_TAG_RESOURCES, "Bitmap.compress");
        boolean result = nativeCompress(mNativePtr, format.nativeInt,
                quality, stream, new byte[WORKING_COMPRESS_STORAGE]);
        Trace.traceEnd(Trace.TRACE_TAG_RESOURCES);
        return result;
    }
 ```
 
 It clearly indicates that this can be slow. Probably it is faster than sending it over to Flutter and compressing it there, but it might be blocking. 
 Please read this https://github.com/flutter/flutter/issues/22024#issuecomment-465289341
 and all below. 
 
 It states that all the plugin calls run on the UI Thread. You could build in a 
 ```
 Thread.sleep(10000);
 ```
 so simulate what would happen if this is laggy.
 
 So my suggestion is that we use a Worker Thread for this.