Adblocker extension
xaynetwork/plugins pull request #9
Opened 2021-04-20 15:03 UTC by joecks

The Adblock extension:

- accepts a map of BlockRules
- BlockRules are loaded on iOS as json blocking / list of blocked hosts and on Android as rust dat files and list of blocked hosts 
- On Android loading happens on a worker thread
- On iOS code is written and integrated with swift to allow to transform and maintain code in a human readable language
- please review commit by commit, they are in logical order (you find many more infos in the Commit messages)

2021-04-20 20:32 UTC, peterstojanowski requested changes

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +enum ContentBlockingKeys : String {
Formatting issue: space between enum name and colon. Please remove everywhere in Swift files.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +    @objc public static let shared = ContentBlocker();
Remove semicolon at the end. They are not required in Swift.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +@objc public class ContentBlocker : NSObject, ContentBlockerApi  {
Formatting issue: 2 spaces before `{`

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +class ContentBlockerIos11 : ContentBlockerApi {
Do not include iOS version number in the method name.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +        NSLog("Content Blocking is not available for iOS prior 11");
In Swift we use `print` instead of `NSLog`. Please update everywhere.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +            switch rule.value[ContentBlockingKeys.type.rawValue] as! String {
`as! String` can be omitted.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +                self.addContentBlocker(key: res.key, webview: webview)
`self` can be omitted.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +        if compiledLists[key] != nil {
Please use `guard` instead of `if`.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +        if compiledLists[key] != nil {
Please use `guard` instead of `if`.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +                                        if error != nil {
In Swift there is a special syntax for this:
```
if let error = error {

}
```

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +        let formattedHosts = hosts.map { (host) -> String in
This can be simplified:
```
let formattedHosts = hosts.map { "\"\($0)\"" }
.joined(separator: ",")
```

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +                                        completion(ContentBlockerOperationResult.success)
`completion(.success)`

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +enum ContentBlockingRuleTypes : String {
This can be simplified:
```
enum ContentBlockingRuleType: String {
     case json
     case dat
     case hosts 
 }
```

Also, for enum name please use singular version: `ContentBlockingRuleType`

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +    case file_path = "file_path"
`case filePath = "file_path"`

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +    case error_can_not_read_file = 1
Please use camel case names.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +        compileJson(key: key, jsonString : jsonString, completion: completion)
This can be moved up to inside `do`. This way you won't have to declare `jsonString` in a separate line.

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/example/lib/main.dart
> +              "lb.usemaxserver.de",
Shouldn't these hosts come from somewhere else?

2021-04-20 20:32 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +                continue
`continue` can be removed.

2021-04-21 06:06 UTC, joecks commented on packages/webview_flutter/example/lib/main.dart
> +              "lb.usemaxserver.de",
That is just an example to show how it works. Not really crucial.

2021-04-21 07:04 UTC, joecks commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +
done

2021-04-21 07:13 UTC, joecks commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +            switch rule.value[ContentBlockingKeys.type.rawValue] as! String {
No it can not
`Value of protocol type 'Any' cannot conform to 'Equatable'; only struct/enum/class types can conform to protocols`

2021-04-21 07:21 UTC, joecks commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +                self.addContentBlocker(key: res.key, webview: webview)
Call to method 'addContentBlocker' in closure requires explicit use of 'self' to make capture semantics explicit

2021-04-21 07:27 UTC, joecks commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +        if compiledLists[key] != nil {
Guard does not make sense here. It requires an else part but I am not guarding against nil but I am stopping execution if the value is not set, thus it is wanted.

afaik: 

```swift
guard number >= 0 else {
        return nil
    }
```

is to guard like assert which is not the case here

2021-04-21 07:30 UTC, joecks commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +        if compiledLists[key] != nil {
again same thing as before. Maybe you could show me how it should look like in your opinion.

2021-04-21 07:45 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +        if compiledLists[key] != nil {
`guard` in Swift is used when you want to return early and to avoid unnecessary indentation later. It's a good practice and does make sense.

2021-04-21 07:56 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +            switch rule.value[ContentBlockingKeys.type.rawValue] as! String {
Ok, but in this case how do I know that the value will be a `String` and it's safe to unwrap? This probably should be refactored to be type safe.

2021-04-21 07:57 UTC, peterstojanowski commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +                self.addContentBlocker(key: res.key, webview: webview)
Cool. Didn't notice that this is inside a block.

2021-04-21 09:35 UTC, joecks commented on packages/webview_flutter/ios/Classes/ContentBlocker.swift
> +            switch rule.value[ContentBlockingKeys.type.rawValue] as! String {
That is the behavior all along in the webview. Each time we access the params that come from flutter we don't know their type, we just know how it used to be implemented. So I can add some asserts or guards but that would also crash in this scenario.

2021-04-21 15:06 UTC, peterstojanowski approved these changes
iOS part looks good!

2021-04-24 12:36 UTC, merged